version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: config/nginx/Dockerfile
    ports:
      - '8080:80'
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    build:
      context: .
      dockerfile: config/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: tutoseu
      MYSQL_DATABASE: db-MamaMia
      MYSQL_USER: myuser
      MYSQL_PASSWORD: monpassword
    ports:
      - 3306:3306
    networks:
      - internal

networks:
  internal:
    driver: bridge